export const AssetId = {
    THREE_TEXTURE_TEMPLATE: 'THREE_TEXTURE_TEMPLATE',
    THREE_HDR_TEMPLATE: 'THREE_HDR_TEMPLATE',
    THREE_GLTF_TEMPLATE: 'THREE_GLTF_TEMPLATE',
    THREE_FONT_TEMPLATE: 'THREE_FONT_TEMPLATE',

    THREE_HDR_1: 'THREE_HDR_1',
    THREE_HDR_2: 'THREE_HDR_2',
    THREE_HDR_3: 'THREE_HDR_3',
    THREE_GLTF_DUNES: 'THREE_GLTF_DUNES',
    THREE_TEXTURE_DUNES_ARM: 'THREE_TEXTURE_DUNES_ARM',
    THREE_TEXTURE_DUNES_NORMAL: 'THREE_TEXTURE_DUNES_NORMAL',
    THREE_GLTF_JELLY: 'THREE_GLTF_JELLY',
} as const;

export type AssetId = (typeof AssetId)[keyof typeof AssetId];
